P.when("A").register("reg-jquery-ui-sortable",function(p){p=p.$;(function(b,n){function r(c,a){var d;d=c.nodeName.toLowerCase();if("area"===d){a=c.parentNode;d=a.name;if(!c.href||!d||"map"!==a.nodeName.toLowerCase())return!1;c=b("img[usemap\x3d#"+d+"]")[0];return!!c&&g(c)}return(/input|select|textarea|button|object/.test(d)?!c.disabled:"a"===d?c.href||a:a)&&g(c)}function g(c){return b.expr.filters.visible(c)&&!b(c).parents().addBack().filter(function(){return"hidden"===b.css(this,"visibility")}).length}
var a=0,d=/^ui-id-\d+$/;b.ui=b.ui||{};b.extend(b.ui,{version:"1.10.4",keyCode:{BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38}});b.fn.extend({focus:function(c){return function(a,d){return"number"===typeof a?this.each(function(){var c=this;setTimeout(function(){b(c).focus();d&&d.call(c)},a)}):
c.apply(this,arguments)}}(b.fn.focus),scrollParent:function(){var c;c=b.ui.ie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.css(this,"position"))&&/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0);
return/fixed/.test(this.css("position"))||!c.length?b(document):c},zIndex:function(c){if(c!==n)return this.css("zIndex",c);if(this.length){c=b(this[0]);for(var a;c.length&&c[0]!==document;){a=c.css("position");if("absolute"===a||"relative"===a||"fixed"===a)if(a=parseInt(c.css("zIndex"),10),!isNaN(a)&&0!==a)return a;c=c.parent()}}return 0},uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++a)})},removeUniqueId:function(){return this.each(function(){d.test(this.id)&&b(this).removeAttr("id")})}});
b.extend(b.expr[":"],{data:b.expr.createPseudo?b.expr.createPseudo(function(c){return function(a){return!!b.data(a,c)}}):function(a,d,f){return!!b.data(a,f[3])},focusable:function(a){return r(a,!isNaN(b.attr(a,"tabindex")))},tabbable:function(a){var d=b.attr(a,"tabindex"),f=isNaN(d);return(f||0<=d)&&r(a,!f)}});b("\x3ca\x3e").outerWidth(1).jquery||b.each(["Width","Height"],function(a,d){function f(a,d,c,e){b.each(h,function(){d-=parseFloat(b.css(a,"padding"+this))||0;c&&(d-=parseFloat(b.css(a,"border"+
this+"Width"))||0);e&&(d-=parseFloat(b.css(a,"margin"+this))||0)});return d}var h="Width"===d?["Left","Right"]:["Top","Bottom"],k=d.toLowerCase(),l={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+d]=function(a){return a===n?l["inner"+d].call(this):this.each(function(){b(this).css(k,f(this,a)+"px")})};b.fn["outer"+d]=function(a,c){return"number"!==typeof a?l["outer"+d].call(this,a):this.each(function(){b(this).css(k,f(this,
a,!0,c)+"px")})}});b.fn.addBack||(b.fn.addBack=function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))});b("\x3ca\x3e").data("a-b","a").removeData("a-b").data("a-b")&&(b.fn.removeData=function(a){return function(d){return arguments.length?a.call(this,b.camelCase(d)):a.call(this)}}(b.fn.removeData));b.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());b.support.selectstart="onselectstart"in document.createElement("div");b.fn.extend({disableSelection:function(){return this.bind((b.support.selectstart?
"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.extend(b.ui,{plugin:{add:function(a,d,f){var h;a=b.ui[a].prototype;for(h in f)a.plugins[h]=a.plugins[h]||[],a.plugins[h].push([d,f[h]])},call:function(a,d,b){var h=a.plugins[d];if(h&&a.element[0].parentNode&&11!==a.element[0].parentNode.nodeType)for(d=0;d<h.length;d++)a.options[h[d][0]]&&h[d][1].apply(a.element,b)}},hasScroll:function(a,d){if("hidden"===
b(a).css("overflow"))return!1;d=d&&"left"===d?"scrollLeft":"scrollTop";var f;if(0<a[d])return!0;a[d]=1;f=0<a[d];a[d]=0;return f}})})(p);(function(b,n){var r=0,g=Array.prototype.slice,a=b.cleanData;b.cleanData=function(d){for(var c=0,e;null!=(e=d[c]);c++)try{b(e).triggerHandler("remove")}catch(f){}a(d)};b.widget=function(a,c,e){var f,h,k,l,g={},m=a.split(".")[0];a=a.split(".")[1];f=m+"-"+a;e||(e=c,c=b.Widget);b.expr[":"][f.toLowerCase()]=function(a){return!!b.data(a,f)};b[m]=b[m]||{};h=b[m][a];k=b[m][a]=
function(a,d){if(!this._createWidget)return new k(a,d);arguments.length&&this._createWidget(a,d)};b.extend(k,h,{version:e.version,_proto:b.extend({},e),_childConstructors:[]});l=new c;l.options=b.widget.extend({},l.options);b.each(e,function(a,d){b.isFunction(d)?g[a]=function(){var b=function(){return c.prototype[a].apply(this,arguments)},e=function(d){return c.prototype[a].apply(this,d)};return function(){var a=this._super,c=this._superApply,f;this._super=b;this._superApply=e;f=d.apply(this,arguments);
this._super=a;this._superApply=c;return f}}():g[a]=d});k.prototype=b.widget.extend(l,{widgetEventPrefix:h?l.widgetEventPrefix||a:a},g,{constructor:k,namespace:m,widgetName:a,widgetFullName:f});h?(b.each(h._childConstructors,function(a,d){a=d.prototype;b.widget(a.namespace+"."+a.widgetName,k,d._proto)}),delete h._childConstructors):c._childConstructors.push(k);b.widget.bridge(a,k)};b.widget.extend=function(a){for(var c=g.call(arguments,1),e=0,f=c.length,h,k;e<f;e++)for(h in c[e])k=c[e][h],c[e].hasOwnProperty(h)&&
k!==n&&(b.isPlainObject(k)?a[h]=b.isPlainObject(a[h])?b.widget.extend({},a[h],k):b.widget.extend({},k):a[h]=k);return a};b.widget.bridge=function(a,c){var e=c.prototype.widgetFullName||a;b.fn[a]=function(f){var h="string"===typeof f,k=g.call(arguments,1),l=this;f=!h&&k.length?b.widget.extend.apply(null,[f].concat(k)):f;h?this.each(function(){var c,h=b.data(this,e);if(!h)return b.error("cannot call methods on "+a+" prior to initialization; attempted to call method '"+f+"'");if(!b.isFunction(h[f])||
"_"===f.charAt(0))return b.error("no such method '"+f+"' for "+a+" widget instance");c=h[f].apply(h,k);if(c!==h&&c!==n)return l=c&&c.jquery?l.pushStack(c.get()):c,!1}):this.each(function(){var a=b.data(this,e);a?a.option(f||{})._init():b.data(this,e,new c(f,this))});return l}};b.Widget=function(){};b.Widget._childConstructors=[];b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"\x3cdiv\x3e",options:{disabled:!1,create:null},_createWidget:function(a,c){c=b(c||this.defaultElement||
this)[0];this.element=b(c);this.uuid=r++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=b.widget.extend({},this.options,this._getCreateOptions(),a);this.bindings=b();this.hoverable=b();this.focusable=b();c!==this&&(b.data(c,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===c&&this.destroy()}}),this.document=b(c.style?c.ownerDocument:c.document||c),this.window=b(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",
null,this._getCreateEventData());this._init()},_getCreateOptions:b.noop,_getCreateEventData:b.noop,_create:b.noop,_init:b.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(b.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");
this.focusable.removeClass("ui-state-focus")},_destroy:b.noop,widget:function(){return this.element},option:function(a,c){var e=a,f,h,k;if(0===arguments.length)return b.widget.extend({},this.options);if("string"===typeof a)if(e={},f=a.split("."),a=f.shift(),f.length){h=e[a]=b.widget.extend({},this.options[a]);for(k=0;k<f.length-1;k++)h[f[k]]=h[f[k]]||{},h=h[f[k]];a=f.pop();if(1===arguments.length)return h[a]===n?null:h[a];h[a]=c}else{if(1===arguments.length)return this.options[a]===n?null:this.options[a];
e[a]=c}this._setOptions(e);return this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,b){this.options[a]=b;"disabled"===a&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!b).attr("aria-disabled",b),this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus"));return this},enable:function(){return this._setOption("disabled",!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(a,
c,e){var f,h=this;"boolean"!==typeof a&&(e=c,c=a,a=!1);e?(c=f=b(c),this.bindings=this.bindings.add(c)):(e=c,c=this.element,f=this.widget());b.each(e,function(e,g){function t(){if(a||!0!==h.options.disabled&&!b(this).hasClass("ui-state-disabled"))return("string"===typeof g?h[g]:g).apply(h,arguments)}"string"!==typeof g&&(t.guid=g.guid=g.guid||t.guid||b.guid++);var m=e.match(/^(\w+)\s*(.*)$/);e=m[1]+h.eventNamespace;(m=m[2])?f.delegate(m,e,t):c.bind(e,t)})},_off:function(a,b){b=(b||"").split(" ").join(this.eventNamespace+
" ")+this.eventNamespace;a.unbind(b).undelegate(b)},_delay:function(a,b){var e=this;return setTimeout(function(){return("string"===typeof a?e[a]:a).apply(e,arguments)},b||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){b(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){b(a.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){b(a.currentTarget).addClass("ui-state-focus")},
focusout:function(a){b(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(a,c,e){var f,h=this.options[a];e=e||{};c=b.Event(c);c.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();c.target=this.element[0];if(a=c.originalEvent)for(f in a)f in c||(c[f]=a[f]);this.element.trigger(c,e);return!(b.isFunction(h)&&!1===h.apply(this.element[0],[c].concat(e))||c.isDefaultPrevented())}};b.each({show:"fadeIn",hide:"fadeOut"},function(a,c){b.Widget.prototype["_"+a]=function(e,
f,h){"string"===typeof f&&(f={effect:f});var k,g=f?!0===f||"number"===typeof f?c:f.effect||c:a;f=f||{};"number"===typeof f&&(f={duration:f});k=!b.isEmptyObject(f);f.complete=h;f.delay&&e.delay(f.delay);if(k&&b.effects&&b.effects.effect[g])e[a](f);else if(g!==a&&e[g])e[g](f.duration,f.easing,h);else e.queue(function(c){b(this)[a]();h&&h.call(e[0]);c()})}})})(p);(function(b,n){var r=!1;b(document).mouseup(function(){r=!1});b.widget("ui.mouse",{version:"1.10.4",options:{cancel:"input,textarea,button,select,option",
distance:1,delay:0},_mouseInit:function(){var g=this;this.element.bind("mousedown."+this.widgetName,function(a){return g._mouseDown(a)}).bind("click."+this.widgetName,function(a){if(!0===b.data(a.target,g.widgetName+".preventClickEvent"))return b.removeData(a.target,g.widgetName+".preventClickEvent"),a.stopImmediatePropagation(),!1});this.started=!1},_mouseDestroy:function(){this.element.unbind("."+this.widgetName);this._mouseMoveDelegate&&b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+
this.widgetName,this._mouseUpDelegate)},_mouseDown:function(g){if(!r){this._mouseStarted&&this._mouseUp(g);this._mouseDownEvent=g;var a=this,d=1===g.which,c="string"===typeof this.options.cancel&&g.target.nodeName?b(g.target).closest(this.options.cancel).length:!1;if(!d||c||!this._mouseCapture(g))return!0;this.mouseDelayMet=!this.options.delay;this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){a.mouseDelayMet=!0},this.options.delay));if(this._mouseDistanceMet(g)&&this._mouseDelayMet(g)&&
(this._mouseStarted=!1!==this._mouseStart(g),!this._mouseStarted))return g.preventDefault(),!0;!0===b.data(g.target,this.widgetName+".preventClickEvent")&&b.removeData(g.target,this.widgetName+".preventClickEvent");this._mouseMoveDelegate=function(b){return a._mouseMove(b)};this._mouseUpDelegate=function(b){return a._mouseUp(b)};b(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);g.preventDefault();return r=!0}},_mouseMove:function(g){if(b.ui.ie&&
(!document.documentMode||9>document.documentMode)&&!g.button)return this._mouseUp(g);if(this._mouseStarted)return this._mouseDrag(g),g.preventDefault();this._mouseDistanceMet(g)&&this._mouseDelayMet(g)&&((this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,g))?this._mouseDrag(g):this._mouseUp(g));return!this._mouseStarted},_mouseUp:function(g){b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&
(this._mouseStarted=!1,g.target===this._mouseDownEvent.target&&b.data(g.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(g));return!1},_mouseDistanceMet:function(b){return Math.max(Math.abs(this._mouseDownEvent.pageX-b.pageX),Math.abs(this._mouseDownEvent.pageY-b.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}})})(p);(function(b,n){function r(a,
b,c){return[parseFloat(a[0])*(t.test(a[0])?b/100:1),parseFloat(a[1])*(t.test(a[1])?c/100:1)]}function g(a){var c=a[0];return 9===c.nodeType?{width:a.width(),height:a.height(),offset:{top:0,left:0}}:b.isWindow(c)?{width:a.width(),height:a.height(),offset:{top:a.scrollTop(),left:a.scrollLeft()}}:c.preventDefault?{width:0,height:0,offset:{top:c.pageY,left:c.pageX}}:{width:a.outerWidth(),height:a.outerHeight(),offset:a.offset()}}b.ui=b.ui||{};var a,d=Math.max,c=Math.abs,e=Math.round,f=/left|center|right/,
h=/top|center|bottom/,k=/[\+\-]\d+(\.[\d]+)?%?/,l=/^\w+/,t=/%$/,m=b.fn.position;b.position={scrollbarWidth:function(){if(a!==n)return a;var c,d,e=b("\x3cdiv style\x3d'display:block;position:absolute;width:50px;height:50px;overflow:hidden;'\x3e\x3cdiv style\x3d'height:100px;width:auto;'\x3e\x3c/div\x3e\x3c/div\x3e");d=e.children()[0];b("body").append(e);c=d.offsetWidth;e.css("overflow","scroll");d=d.offsetWidth;c===d&&(d=e[0].clientWidth);e.remove();return a=c-d},getScrollInfo:function(a){var c=a.isWindow||
a.isDocument?"":a.element.css("overflow-x"),d=a.isWindow||a.isDocument?"":a.element.css("overflow-y"),c="scroll"===c||"auto"===c&&a.width<a.element[0].scrollWidth;return{width:"scroll"===d||"auto"===d&&a.height<a.element[0].scrollHeight?b.position.scrollbarWidth():0,height:c?b.position.scrollbarWidth():0}},getWithinInfo:function(a){a=b(a||window);var c=b.isWindow(a[0]);return{element:a,isWindow:c,isDocument:!!a[0]&&9===a[0].nodeType,offset:a.offset()||{left:0,top:0},scrollLeft:a.scrollLeft(),scrollTop:a.scrollTop(),
width:c?a.width():a.outerWidth(),height:c?a.height():a.outerHeight()}}};b.fn.position=function(a){if(!a||!a.of)return m.apply(this,arguments);a=b.extend({},a);var w,x,y,z,u,v,t=b(a.of),B=b.position.getWithinInfo(a.within),C=b.position.getScrollInfo(B),n=(a.collision||"flip").split(" "),p={};v=g(t);t[0].preventDefault&&(a.at="left top");x=v.width;y=v.height;z=v.offset;u=b.extend({},z);b.each(["my","at"],function(){var b=(a[this]||"").split(" "),c,d;1===b.length&&(b=f.test(b[0])?b.concat(["center"]):
h.test(b[0])?["center"].concat(b):["center","center"]);b[0]=f.test(b[0])?b[0]:"center";b[1]=h.test(b[1])?b[1]:"center";c=k.exec(b[0]);d=k.exec(b[1]);p[this]=[c?c[0]:0,d?d[0]:0];a[this]=[l.exec(b[0])[0],l.exec(b[1])[0]]});1===n.length&&(n[1]=n[0]);"right"===a.at[0]?u.left+=x:"center"===a.at[0]&&(u.left+=x/2);"bottom"===a.at[1]?u.top+=y:"center"===a.at[1]&&(u.top+=y/2);w=r(p.at,x,y);u.left+=w[0];u.top+=w[1];return this.each(function(){var f,h,g=b(this),k=g.outerWidth(),l=g.outerHeight(),v=parseInt(b.css(this,
"marginLeft"),10)||0,m=parseInt(b.css(this,"marginTop"),10)||0,D=k+v+(parseInt(b.css(this,"marginRight"),10)||0)+C.width,E=l+m+(parseInt(b.css(this,"marginBottom"),10)||0)+C.height,q=b.extend({},u),A=r(p.my,g.outerWidth(),g.outerHeight());"right"===a.my[0]?q.left-=k:"center"===a.my[0]&&(q.left-=k/2);"bottom"===a.my[1]?q.top-=l:"center"===a.my[1]&&(q.top-=l/2);q.left+=A[0];q.top+=A[1];b.support.offsetFractions||(q.left=e(q.left),q.top=e(q.top));f={marginLeft:v,marginTop:m};b.each(["left","top"],function(c,
d){if(b.ui.position[n[c]])b.ui.position[n[c]][d](q,{targetWidth:x,targetHeight:y,elemWidth:k,elemHeight:l,collisionPosition:f,collisionWidth:D,collisionHeight:E,offset:[w[0]+A[0],w[1]+A[1]],my:a.my,at:a.at,within:B,elem:g})});a.using&&(h=function(b){var e=z.left-q.left,f=e+x-k,h=z.top-q.top,w=h+y-l,v={target:{element:t,left:z.left,top:z.top,width:x,height:y},element:{element:g,left:q.left,top:q.top,width:k,height:l},horizontal:0>f?"left":0<e?"right":"center",vertical:0>w?"top":0<h?"bottom":"middle"};
x<k&&c(e+f)<x&&(v.horizontal="center");y<l&&c(h+w)<y&&(v.vertical="middle");d(c(e),c(f))>d(c(h),c(w))?v.important="horizontal":v.important="vertical";a.using.call(this,b,v)});g.offset(b.extend(q,{using:h}))})};b.ui.position={fit:{left:function(a,b){var c=b.within,e=c.isWindow?c.scrollLeft:c.offset.left,f=c.width,h=a.left-b.collisionPosition.marginLeft,c=e-h,g=h+b.collisionWidth-f-e;b.collisionWidth>f?0<c&&0>=g?(b=a.left+c+b.collisionWidth-f-e,a.left+=c-b):a.left=0<g&&0>=c?e:c>g?e+f-b.collisionWidth:
e:a.left=0<c?a.left+c:0<g?a.left-g:d(a.left-h,a.left)},top:function(a,b){var c=b.within,e=c.isWindow?c.scrollTop:c.offset.top,f=b.within.height,h=a.top-b.collisionPosition.marginTop,c=e-h,g=h+b.collisionHeight-f-e;b.collisionHeight>f?0<c&&0>=g?(b=a.top+c+b.collisionHeight-f-e,a.top+=c-b):a.top=0<g&&0>=c?e:c>g?e+f-b.collisionHeight:e:a.top=0<c?a.top+c:0<g?a.top-g:d(a.top-h,a.top)}},flip:{left:function(a,b){var d=b.within,e=d.offset.left+d.scrollLeft,f=d.width,h=d.isWindow?d.scrollLeft:d.offset.left,
g=a.left-b.collisionPosition.marginLeft,d=g-h,k=g+b.collisionWidth-f-h,g="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,l="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,m=-2*b.offset[0];if(0>d){if(b=a.left+g+l+m+b.collisionWidth-f-e,0>b||b<c(d))a.left+=g+l+m}else 0<k&&(b=a.left-b.collisionPosition.marginLeft+g+l+m-h,0<b||c(b)<k)&&(a.left+=g+l+m)},top:function(a,b){var d=b.within,e=d.offset.top+d.scrollTop,f=d.height,h=d.isWindow?d.scrollTop:d.offset.top,g=a.top-b.collisionPosition.marginTop,
d=g-h,k=g+b.collisionHeight-f-h,g="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,l="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,m=-2*b.offset[1];0>d?(b=a.top+g+l+m+b.collisionHeight-f-e,a.top+g+l+m>d&&(0>b||b<c(d))&&(a.top+=g+l+m)):0<k&&(b=a.top-b.collisionPosition.marginTop+g+l+m-h,a.top+g+l+m>k&&(0<b||c(b)<k)&&(a.top+=g+l+m))}},flipfit:{left:function(){b.ui.position.flip.left.apply(this,arguments);b.ui.position.fit.left.apply(this,arguments)},top:function(){b.ui.position.flip.top.apply(this,
arguments);b.ui.position.fit.top.apply(this,arguments)}}};(function(){var a,c,d,e,f=document.getElementsByTagName("body")[0];d=document.createElement("div");a=document.createElement(f?"div":"body");c={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};f&&b.extend(c,{position:"absolute",left:"-1000px",top:"-1000px"});for(e in c)a.style[e]=c[e];a.appendChild(d);c=f||document.documentElement;c.insertBefore(a,c.firstChild);d.style.cssText="position: absolute; left: 10.7432222px;";
d=b(d).offset().left;b.support.offsetFractions=10<d&&11>d;a.innerHTML="";c.removeChild(a)})()})(p);(function(b,n){function r(a,b,c){return a>b&&a<b+c}function g(a){return/left|right/.test(a.css("float"))||/inline|table-cell/.test(a.css("display"))}b.widget("ui.sortable",b.ui.mouse,{version:"1.10.4",widgetEventPrefix:"sort",ready:!1,options:{appendTo:"parent",axis:!1,connectWith:!1,containment:!1,cursor:"auto",cursorAt:!1,dropOnEmpty:!0,forcePlaceholderSize:!1,forceHelperSize:!1,grid:!1,handle:!1,
helper:"original",items:"\x3e *",opacity:!1,placeholder:!1,revert:!1,scroll:!0,scrollSensitivity:20,scrollSpeed:20,scope:"default",tolerance:"intersect",zIndex:1E3,activate:null,beforeStop:null,change:null,deactivate:null,out:null,over:null,receive:null,remove:null,sort:null,start:null,stop:null,update:null},_create:function(){var a=this.options;this.containerCache={};this.element.addClass("ui-sortable");this.refresh();this.floating=this.items.length?"x"===a.axis||g(this.items[0].item):!1;this.offset=
this.element.offset();this._mouseInit();this.ready=!0},_destroy:function(){this.element.removeClass("ui-sortable ui-sortable-disabled");this._mouseDestroy();for(var a=this.items.length-1;0<=a;a--)this.items[a].item.removeData(this.widgetName+"-item");return this},_setOption:function(a,d){"disabled"===a?(this.options[a]=d,this.widget().toggleClass("ui-sortable-disabled",!!d)):b.Widget.prototype._setOption.apply(this,arguments)},_mouseCapture:function(a,d){var c=null,e=!1,f=this;if(this.reverting||
this.options.disabled||"static"===this.options.type)return!1;this._refreshItems(a);b(a.target).parents().each(function(){if(b.data(this,f.widgetName+"-item")===f)return c=b(this),!1});b.data(a.target,f.widgetName+"-item")===f&&(c=b(a.target));if(!c||this.options.handle&&!d&&(b(this.options.handle,c).find("*").addBack().each(function(){this===a.target&&(e=!0)}),!e))return!1;this.currentItem=c;this._removeCurrentsFromItems();return!0},_mouseStart:function(a,d,c){var e;d=this.options;this.currentContainer=
this;this.refreshPositions();this.helper=this._createHelper(a);this._cacheHelperProportions();this._cacheMargins();this.scrollParent=this.helper.scrollParent();this.offset=this.currentItem.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};b.extend(this.offset,{click:{left:a.pageX-this.offset.left,top:a.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.helper.css("position","absolute");this.cssPosition=
this.helper.css("position");this.originalPosition=this._generatePosition(a);this.originalPageX=a.pageX;this.originalPageY=a.pageY;d.cursorAt&&this._adjustOffsetFromHelper(d.cursorAt);this.domPosition={prev:this.currentItem.prev()[0],parent:this.currentItem.parent()[0]};this.helper[0]!==this.currentItem[0]&&this.currentItem.hide();this._createPlaceholder();d.containment&&this._setContainment();d.cursor&&"auto"!==d.cursor&&(e=this.document.find("body"),this.storedCursor=e.css("cursor"),e.css("cursor",
d.cursor),this.storedStylesheet=b("\x3cstyle\x3e*{ cursor: "+d.cursor+" !important; }\x3c/style\x3e").appendTo(e));d.opacity&&(this.helper.css("opacity")&&(this._storedOpacity=this.helper.css("opacity")),this.helper.css("opacity",d.opacity));d.zIndex&&(this.helper.css("zIndex")&&(this._storedZIndex=this.helper.css("zIndex")),this.helper.css("zIndex",d.zIndex));this.scrollParent[0]!==document&&"HTML"!==this.scrollParent[0].tagName&&(this.overflowOffset=this.scrollParent.offset());this._trigger("start",
a,this._uiHash());this._preserveHelperProportions||this._cacheHelperProportions();if(!c)for(c=this.containers.length-1;0<=c;c--)this.containers[c]._trigger("activate",a,this._uiHash(this));b.ui.ddmanager&&(b.ui.ddmanager.current=this);b.ui.ddmanager&&!d.dropBehaviour&&b.ui.ddmanager.prepareOffsets(this,a);this.dragging=!0;this.helper.addClass("ui-sortable-helper");this._mouseDrag(a);return!0},_mouseDrag:function(a){var d,c,e,f;d=this.options;c=!1;this.position=this._generatePosition(a);this.positionAbs=
this._convertPositionTo("absolute");this.lastPositionAbs||(this.lastPositionAbs=this.positionAbs);this.options.scroll&&(this.scrollParent[0]!==document&&"HTML"!==this.scrollParent[0].tagName?(this.overflowOffset.top+this.scrollParent[0].offsetHeight-a.pageY<d.scrollSensitivity?this.scrollParent[0].scrollTop=c=this.scrollParent[0].scrollTop+d.scrollSpeed:a.pageY-this.overflowOffset.top<d.scrollSensitivity&&(this.scrollParent[0].scrollTop=c=this.scrollParent[0].scrollTop-d.scrollSpeed),this.overflowOffset.left+
this.scrollParent[0].offsetWidth-a.pageX<d.scrollSensitivity?this.scrollParent[0].scrollLeft=c=this.scrollParent[0].scrollLeft+d.scrollSpeed:a.pageX-this.overflowOffset.left<d.scrollSensitivity&&(this.scrollParent[0].scrollLeft=c=this.scrollParent[0].scrollLeft-d.scrollSpeed)):(a.pageY-b(document).scrollTop()<d.scrollSensitivity?c=b(document).scrollTop(b(document).scrollTop()-d.scrollSpeed):b(window).height()-(a.pageY-b(document).scrollTop())<d.scrollSensitivity&&(c=b(document).scrollTop(b(document).scrollTop()+
d.scrollSpeed)),a.pageX-b(document).scrollLeft()<d.scrollSensitivity?c=b(document).scrollLeft(b(document).scrollLeft()-d.scrollSpeed):b(window).width()-(a.pageX-b(document).scrollLeft())<d.scrollSensitivity&&(c=b(document).scrollLeft(b(document).scrollLeft()+d.scrollSpeed))),!1!==c&&b.ui.ddmanager&&!d.dropBehaviour&&b.ui.ddmanager.prepareOffsets(this,a));this.positionAbs=this._convertPositionTo("absolute");this.options.axis&&"y"===this.options.axis||(this.helper[0].style.left=this.position.left+"px");
this.options.axis&&"x"===this.options.axis||(this.helper[0].style.top=this.position.top+"px");for(d=this.items.length-1;0<=d;d--)if(c=this.items[d],e=c.item[0],(f=this._intersectsWithPointer(c))&&c.instance===this.currentContainer&&e!==this.currentItem[0]&&this.placeholder[1===f?"next":"prev"]()[0]!==e&&!b.contains(this.placeholder[0],e)&&("semi-dynamic"===this.options.type?!b.contains(this.element[0],e):1)){this.direction=1===f?"down":"up";if("pointer"===this.options.tolerance||this._intersectsWithSides(c))this._rearrange(a,
c);else break;this._trigger("change",a,this._uiHash());break}this._contactContainers(a);b.ui.ddmanager&&b.ui.ddmanager.drag(this,a);this._trigger("sort",a,this._uiHash());this.lastPositionAbs=this.positionAbs;return!1},_mouseStop:function(a,d){if(a){b.ui.ddmanager&&!this.options.dropBehaviour&&b.ui.ddmanager.drop(this,a);if(this.options.revert){var c=this;d=this.placeholder.offset();var e=this.options.axis,f={};e&&"x"!==e||(f.left=d.left-this.offset.parent.left-this.margins.left+(this.offsetParent[0]===
document.body?0:this.offsetParent[0].scrollLeft));e&&"y"!==e||(f.top=d.top-this.offset.parent.top-this.margins.top+(this.offsetParent[0]===document.body?0:this.offsetParent[0].scrollTop));this.reverting=!0;b(this.helper).animate(f,parseInt(this.options.revert,10)||500,function(){c._clear(a)})}else this._clear(a,d);return!1}},cancel:function(){if(this.dragging){this._mouseUp({target:null});"original"===this.options.helper?this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper"):this.currentItem.show();
for(var a=this.containers.length-1;0<=a;a--)this.containers[a]._trigger("deactivate",null,this._uiHash(this)),this.containers[a].containerCache.over&&(this.containers[a]._trigger("out",null,this._uiHash(this)),this.containers[a].containerCache.over=0)}this.placeholder&&(this.placeholder[0].parentNode&&this.placeholder[0].parentNode.removeChild(this.placeholder[0]),"original"!==this.options.helper&&this.helper&&this.helper[0].parentNode&&this.helper.remove(),b.extend(this,{helper:null,dragging:!1,
reverting:!1,_noFinalSort:null}),this.domPosition.prev?b(this.domPosition.prev).after(this.currentItem):b(this.domPosition.parent).prepend(this.currentItem));return this},serialize:function(a){var d=this._getItemsAsjQuery(a&&a.connected),c=[];a=a||{};b(d).each(function(){var d=(b(a.item||this).attr(a.attribute||"id")||"").match(a.expression||/(.+)[\-=_](.+)/);d&&c.push((a.key||d[1]+"[]")+"\x3d"+(a.key&&a.expression?d[1]:d[2]))});!c.length&&a.key&&c.push(a.key+"\x3d");return c.join("\x26")},toArray:function(a){var d=
this._getItemsAsjQuery(a&&a.connected),c=[];a=a||{};d.each(function(){c.push(b(a.item||this).attr(a.attribute||"id")||"")});return c},_intersectsWith:function(a){var b=this.positionAbs.left,c=b+this.helperProportions.width,e=this.positionAbs.top,f=e+this.helperProportions.height,h=a.left,g=h+a.width,l=a.top,t=l+a.height,m=this.offset.click.top,n=this.offset.click.left,m="x"===this.options.axis||e+m>l&&e+m<t,n="y"===this.options.axis||b+n>h&&b+n<g;return"pointer"===this.options.tolerance||this.options.forcePointerForContainers||
"pointer"!==this.options.tolerance&&this.helperProportions[this.floating?"width":"height"]>a[this.floating?"width":"height"]?m&&n:h<b+this.helperProportions.width/2&&c-this.helperProportions.width/2<g&&l<e+this.helperProportions.height/2&&f-this.helperProportions.height/2<t},_intersectsWithPointer:function(a){var b="x"===this.options.axis||r(this.positionAbs.top+this.offset.click.top,a.top,a.height);a="y"===this.options.axis||r(this.positionAbs.left+this.offset.click.left,a.left,a.width);b=b&&a;a=
this._getDragVerticalDirection();var c=this._getDragHorizontalDirection();return b?this.floating?c&&"right"===c||"down"===a?2:1:a&&("down"===a?2:1):!1},_intersectsWithSides:function(a){var b=r(this.positionAbs.top+this.offset.click.top,a.top+a.height/2,a.height);a=r(this.positionAbs.left+this.offset.click.left,a.left+a.width/2,a.width);var c=this._getDragVerticalDirection(),e=this._getDragHorizontalDirection();return this.floating&&e?"right"===e&&a||"left"===e&&!a:c&&("down"===c&&b||"up"===c&&!b)},
_getDragVerticalDirection:function(){var a=this.positionAbs.top-this.lastPositionAbs.top;return 0!==a&&(0<a?"down":"up")},_getDragHorizontalDirection:function(){var a=this.positionAbs.left-this.lastPositionAbs.left;return 0!==a&&(0<a?"right":"left")},refresh:function(a){this._refreshItems(a);this.refreshPositions();return this},_connectWith:function(){var a=this.options;return a.connectWith.constructor===String?[a.connectWith]:a.connectWith},_getItemsAsjQuery:function(a){function d(){h.push(this)}
var c,e,f,h=[],g=[],l=this._connectWith();if(l&&a)for(a=l.length-1;0<=a;a--)for(e=b(l[a]),c=e.length-1;0<=c;c--)(f=b.data(e[c],this.widgetFullName))&&f!==this&&!f.options.disabled&&g.push([b.isFunction(f.options.items)?f.options.items.call(f.element):b(f.options.items,f.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),f]);g.push([b.isFunction(this.options.items)?this.options.items.call(this.element,null,{options:this.options,item:this.currentItem}):b(this.options.items,this.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),
this]);for(a=g.length-1;0<=a;a--)g[a][0].each(d);return b(h)},_removeCurrentsFromItems:function(){var a=this.currentItem.find(":data("+this.widgetName+"-item)");this.items=b.grep(this.items,function(b){for(var c=0;c<a.length;c++)if(a[c]===b.item[0])return!1;return!0})},_refreshItems:function(a){this.items=[];this.containers=[this];var d,c,e,f,h,g=this.items,l=[[b.isFunction(this.options.items)?this.options.items.call(this.element[0],a,{item:this.currentItem}):b(this.options.items,this.element),this]];
if((h=this._connectWith())&&this.ready)for(d=h.length-1;0<=d;d--)for(e=b(h[d]),c=e.length-1;0<=c;c--)(f=b.data(e[c],this.widgetFullName))&&f!==this&&!f.options.disabled&&(l.push([b.isFunction(f.options.items)?f.options.items.call(f.element[0],a,{item:this.currentItem}):b(f.options.items,f.element),f]),this.containers.push(f));for(d=l.length-1;0<=d;d--)for(a=l[d][1],e=l[d][0],c=0,h=e.length;c<h;c++)f=b(e[c]),f.data(this.widgetName+"-item",a),g.push({item:f,instance:a,width:0,height:0,left:0,top:0})},
refreshPositions:function(a){this.offsetParent&&this.helper&&(this.offset.parent=this._getParentOffset());var d,c,e;for(d=this.items.length-1;0<=d;d--)c=this.items[d],c.instance!==this.currentContainer&&this.currentContainer&&c.item[0]!==this.currentItem[0]||(e=this.options.toleranceElement?b(this.options.toleranceElement,c.item):c.item,a||(c.width=e.outerWidth(),c.height=e.outerHeight()),e=e.offset(),c.left=e.left,c.top=e.top);if(this.options.custom&&this.options.custom.refreshContainers)this.options.custom.refreshContainers.call(this);
else for(d=this.containers.length-1;0<=d;d--)e=this.containers[d].element.offset(),this.containers[d].containerCache.left=e.left,this.containers[d].containerCache.top=e.top,this.containers[d].containerCache.width=this.containers[d].element.outerWidth(),this.containers[d].containerCache.height=this.containers[d].element.outerHeight();return this},_createPlaceholder:function(a){a=a||this;var d,c=a.options;c.placeholder&&c.placeholder.constructor!==String||(d=c.placeholder,c.placeholder={element:function(){var c=
a.currentItem[0].nodeName.toLowerCase(),f=b("\x3c"+c+"\x3e",a.document[0]).addClass(d||a.currentItem[0].className+" ui-sortable-placeholder").removeClass("ui-sortable-helper");"tr"===c?a.currentItem.children().each(function(){b("\x3ctd\x3e\x26#160;\x3c/td\x3e",a.document[0]).attr("colspan",b(this).attr("colspan")||1).appendTo(f)}):"img"===c&&f.attr("src",a.currentItem.attr("src"));d||f.css("visibility","hidden");return f},update:function(b,f){if(!d||c.forcePlaceholderSize)f.height()||f.height(a.currentItem.innerHeight()-
parseInt(a.currentItem.css("paddingTop")||0,10)-parseInt(a.currentItem.css("paddingBottom")||0,10)),f.width()||f.width(a.currentItem.innerWidth()-parseInt(a.currentItem.css("paddingLeft")||0,10)-parseInt(a.currentItem.css("paddingRight")||0,10))}});a.placeholder=b(c.placeholder.element.call(a.element,a.currentItem));a.currentItem.after(a.placeholder);c.placeholder.update(a,a.placeholder)},_contactContainers:function(a){var d,c,e,f,h,k,l,n,m,p=c=null;for(d=this.containers.length-1;0<=d;d--)b.contains(this.currentItem[0],
this.containers[d].element[0])||(this._intersectsWith(this.containers[d].containerCache)?c&&b.contains(this.containers[d].element[0],c.element[0])||(c=this.containers[d],p=d):this.containers[d].containerCache.over&&(this.containers[d]._trigger("out",a,this._uiHash(this)),this.containers[d].containerCache.over=0));if(c)if(1===this.containers.length)this.containers[p].containerCache.over||(this.containers[p]._trigger("over",a,this._uiHash(this)),this.containers[p].containerCache.over=1);else{d=1E4;
e=null;f=(m=c.floating||g(this.currentItem))?"left":"top";h=m?"width":"height";k=this.positionAbs[f]+this.offset.click[f];for(c=this.items.length-1;0<=c;c--)!b.contains(this.containers[p].element[0],this.items[c].item[0])||this.items[c].item[0]===this.currentItem[0]||m&&!r(this.positionAbs.top+this.offset.click.top,this.items[c].top,this.items[c].height)||(l=this.items[c].item.offset()[f],n=!1,Math.abs(l-k)>Math.abs(l+this.items[c][h]-k)&&(n=!0,l+=this.items[c][h]),Math.abs(l-k)<d&&(d=Math.abs(l-
k),e=this.items[c],this.direction=n?"up":"down"));(e||this.options.dropOnEmpty)&&this.currentContainer!==this.containers[p]&&(e?this._rearrange(a,e,null,!0):this._rearrange(a,null,this.containers[p].element,!0),this._trigger("change",a,this._uiHash()),this.containers[p]._trigger("change",a,this._uiHash(this)),this.currentContainer=this.containers[p],this.options.placeholder.update(this.currentContainer,this.placeholder),this.containers[p]._trigger("over",a,this._uiHash(this)),this.containers[p].containerCache.over=
1)}},_createHelper:function(a){var d=this.options;a=b.isFunction(d.helper)?b(d.helper.apply(this.element[0],[a,this.currentItem])):"clone"===d.helper?this.currentItem.clone():this.currentItem;a.parents("body").length||b("parent"!==d.appendTo?d.appendTo:this.currentItem[0].parentNode)[0].appendChild(a[0]);a[0]===this.currentItem[0]&&(this._storedCSS={width:this.currentItem[0].style.width,height:this.currentItem[0].style.height,position:this.currentItem.css("position"),top:this.currentItem.css("top"),
left:this.currentItem.css("left")});a[0].style.width&&!d.forceHelperSize||a.width(this.currentItem.width());a[0].style.height&&!d.forceHelperSize||a.height(this.currentItem.height());return a},_adjustOffsetFromHelper:function(a){"string"===typeof a&&(a=a.split(" "));b.isArray(a)&&(a={left:+a[0],top:+a[1]||0});"left"in a&&(this.offset.click.left=a.left+this.margins.left);"right"in a&&(this.offset.click.left=this.helperProportions.width-a.right+this.margins.left);"top"in a&&(this.offset.click.top=a.top+
this.margins.top);"bottom"in a&&(this.offset.click.top=this.helperProportions.height-a.bottom+this.margins.top)},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var a=this.offsetParent.offset();"absolute"===this.cssPosition&&this.scrollParent[0]!==document&&b.contains(this.scrollParent[0],this.offsetParent[0])&&(a.left+=this.scrollParent.scrollLeft(),a.top+=this.scrollParent.scrollTop());if(this.offsetParent[0]===document.body||this.offsetParent[0].tagName&&"html"===this.offsetParent[0].tagName.toLowerCase()&&
b.ui.ie)a={top:0,left:0};return{top:a.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:a.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if("relative"===this.cssPosition){var a=this.currentItem.position();return{top:a.top-(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}return{top:0,left:0}},_cacheMargins:function(){this.margins=
{left:parseInt(this.currentItem.css("marginLeft"),10)||0,top:parseInt(this.currentItem.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var a,d,c;d=this.options;"parent"===d.containment&&(d.containment=this.helper[0].parentNode);if("document"===d.containment||"window"===d.containment)this.containment=[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-
this.offset.parent.top,b("document"===d.containment?document:window).width()-this.helperProportions.width-this.margins.left,(b("document"===d.containment?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];/^(document|window|parent)$/.test(d.containment)||(a=b(d.containment)[0],d=b(d.containment).offset(),c="hidden"!==b(a).css("overflow"),this.containment=[d.left+(parseInt(b(a).css("borderLeftWidth"),10)||0)+(parseInt(b(a).css("paddingLeft"),
10)||0)-this.margins.left,d.top+(parseInt(b(a).css("borderTopWidth"),10)||0)+(parseInt(b(a).css("paddingTop"),10)||0)-this.margins.top,d.left+(c?Math.max(a.scrollWidth,a.offsetWidth):a.offsetWidth)-(parseInt(b(a).css("borderLeftWidth"),10)||0)-(parseInt(b(a).css("paddingRight"),10)||0)-this.helperProportions.width-this.margins.left,d.top+(c?Math.max(a.scrollHeight,a.offsetHeight):a.offsetHeight)-(parseInt(b(a).css("borderTopWidth"),10)||0)-(parseInt(b(a).css("paddingBottom"),10)||0)-this.helperProportions.height-
this.margins.top])},_convertPositionTo:function(a,d){d||(d=this.position);a="absolute"===a?1:-1;var c="absolute"!==this.cssPosition||this.scrollParent[0]!==document&&b.contains(this.scrollParent[0],this.offsetParent[0])?this.scrollParent:this.offsetParent,e=/(html|body)/i.test(c[0].tagName);return{top:d.top+this.offset.relative.top*a+this.offset.parent.top*a-("fixed"===this.cssPosition?-this.scrollParent.scrollTop():e?0:c.scrollTop())*a,left:d.left+this.offset.relative.left*a+this.offset.parent.left*
a-("fixed"===this.cssPosition?-this.scrollParent.scrollLeft():e?0:c.scrollLeft())*a}},_generatePosition:function(a){var d,c,e=this.options;c=a.pageX;d=a.pageY;var f="absolute"!==this.cssPosition||this.scrollParent[0]!==document&&b.contains(this.scrollParent[0],this.offsetParent[0])?this.scrollParent:this.offsetParent,h=/(html|body)/i.test(f[0].tagName);"relative"!==this.cssPosition||this.scrollParent[0]!==document&&this.scrollParent[0]!==this.offsetParent[0]||(this.offset.relative=this._getRelativeOffset());
this.originalPosition&&(this.containment&&(a.pageX-this.offset.click.left<this.containment[0]&&(c=this.containment[0]+this.offset.click.left),a.pageY-this.offset.click.top<this.containment[1]&&(d=this.containment[1]+this.offset.click.top),a.pageX-this.offset.click.left>this.containment[2]&&(c=this.containment[2]+this.offset.click.left),a.pageY-this.offset.click.top>this.containment[3]&&(d=this.containment[3]+this.offset.click.top)),e.grid&&(d=this.originalPageY+Math.round((d-this.originalPageY)/e.grid[1])*
e.grid[1],d=this.containment?d-this.offset.click.top>=this.containment[1]&&d-this.offset.click.top<=this.containment[3]?d:d-this.offset.click.top>=this.containment[1]?d-e.grid[1]:d+e.grid[1]:d,c=this.originalPageX+Math.round((c-this.originalPageX)/e.grid[0])*e.grid[0],c=this.containment?c-this.offset.click.left>=this.containment[0]&&c-this.offset.click.left<=this.containment[2]?c:c-this.offset.click.left>=this.containment[0]?c-e.grid[0]:c+e.grid[0]:c));return{top:d-this.offset.click.top-this.offset.relative.top-
this.offset.parent.top+("fixed"===this.cssPosition?-this.scrollParent.scrollTop():h?0:f.scrollTop()),left:c-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+("fixed"===this.cssPosition?-this.scrollParent.scrollLeft():h?0:f.scrollLeft())}},_rearrange:function(a,b,c,e){c?c[0].appendChild(this.placeholder[0]):b.item[0].parentNode.insertBefore(this.placeholder[0],"down"===this.direction?b.item[0]:b.item[0].nextSibling);var f=this.counter=this.counter?++this.counter:1;this._delay(function(){f===
this.counter&&this.refreshPositions(!e)})},_clear:function(a,b){function c(a,b,c){return function(d){c._trigger(a,d,b._uiHash(b))}}this.reverting=!1;var e,f=[];!this._noFinalSort&&this.currentItem.parent().length&&this.placeholder.before(this.currentItem);this._noFinalSort=null;if(this.helper[0]===this.currentItem[0]){for(e in this._storedCSS)if("auto"===this._storedCSS[e]||"static"===this._storedCSS[e])this._storedCSS[e]="";this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper")}else this.currentItem.show();
this.fromOutside&&!b&&f.push(function(a){this._trigger("receive",a,this._uiHash(this.fromOutside))});!this.fromOutside&&this.domPosition.prev===this.currentItem.prev().not(".ui-sortable-helper")[0]&&this.domPosition.parent===this.currentItem.parent()[0]||b||f.push(function(a){this._trigger("update",a,this._uiHash())});this===this.currentContainer||b||(f.push(function(a){this._trigger("remove",a,this._uiHash())}),f.push(function(a){return function(b){a._trigger("receive",b,this._uiHash(this))}}.call(this,
this.currentContainer)),f.push(function(a){return function(b){a._trigger("update",b,this._uiHash(this))}}.call(this,this.currentContainer)));for(e=this.containers.length-1;0<=e;e--)b||f.push(c("deactivate",this,this.containers[e])),this.containers[e].containerCache.over&&(f.push(c("out",this,this.containers[e])),this.containers[e].containerCache.over=0);this.storedCursor&&(this.document.find("body").css("cursor",this.storedCursor),this.storedStylesheet.remove());this._storedOpacity&&this.helper.css("opacity",
this._storedOpacity);this._storedZIndex&&this.helper.css("zIndex","auto"===this._storedZIndex?"":this._storedZIndex);this.dragging=!1;if(this.cancelHelperRemoval){if(!b){this._trigger("beforeStop",a,this._uiHash());for(e=0;e<f.length;e++)f[e].call(this,a);this._trigger("stop",a,this._uiHash())}return this.fromOutside=!1}b||this._trigger("beforeStop",a,this._uiHash());this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.helper[0]!==this.currentItem[0]&&this.helper.remove();this.helper=
null;if(!b){for(e=0;e<f.length;e++)f[e].call(this,a);this._trigger("stop",a,this._uiHash())}this.fromOutside=!1;return!0},_trigger:function(){!1===b.Widget.prototype._trigger.apply(this,arguments)&&this.cancel()},_uiHash:function(a){var d=a||this;return{helper:d.helper,placeholder:d.placeholder||b([]),position:d.position,originalPosition:d.originalPosition,offset:d.positionAbs,item:d.currentItem,sender:a?a.element:null}}})})(p)});
/* ******** */
P.when("A","reg-jquery-ui-sortable").register("reg-jquery-ui-touch-punch",function(f){(function(c){function b(a,c){if(!(1<a.originalEvent.touches.length)){a.preventDefault();var b=a.originalEvent.changedTouches[0],d=document.createEvent("MouseEvents");d.initMouseEvent(c,!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);a.target.dispatchEvent(d)}}c.support.touch="ontouchend"in document;if(c.support.touch){var d=c.ui.mouse.prototype,f=d._mouseInit,g=d._mouseDestroy,e;d._touchStart=
function(a){!e&&this._mouseCapture(a.originalEvent.changedTouches[0])&&(e=!0,this._touchMoved=!1,b(a,"mouseover"),b(a,"mousemove"),b(a,"mousedown"))};d._touchMove=function(a){e&&(this._touchMoved=!0,b(a,"mousemove"))};d._touchEnd=function(a){e&&(b(a,"mouseup"),b(a,"mouseout"),this._touchMoved||b(a,"click"),e=!1)};d._mouseInit=function(){this.element.bind({touchstart:c.proxy(this,"_touchStart"),touchmove:c.proxy(this,"_touchMove"),touchend:c.proxy(this,"_touchEnd")});f.call(this)};d._mouseDestroy=
function(){this.element.unbind({touchstart:c.proxy(this,"_touchStart"),touchmove:c.proxy(this,"_touchMove"),touchend:c.proxy(this,"_touchEnd")});g.call(this)}}})(f.$)});
/* ******** */
