// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project peach_gardenia {
  database_type: 'sqlite'
  Note: 'This DB offers case workers a way of creating wishlists for children in foster care which allows people to purchase items on the care worker/childs behalf.'
}

Table nouns {
  organisation_addresses _
  organisation _
  case_worker _
  buyer _
  wish_list _
  wish_list_item _
}

Table verbs {
  log_into "allow case_worker or helper to log into their profile"
  create "case_worker can create wishlist"
  add "case_worker can add item to wishlist"
  remove "case_worker can remove item from wishlist"
  view_for_case_worker "Allow case_worker to view associated wishlist with read/write privileges"
  view_for_buyer "Buyer can view all wishlists (readonly)."
}

Table organisation {
  id integer [pk, increment]
  address foreign_key
  name varchar
  email varchar
  tel varchar
}

Table organisation_address {
  id integer [increment]
  org_name varchar
  type varchar(2) // s for shipping, b for billing sb for shipping and billing
  organisation foreign_key
  name varchar
  street_num integer
  street_name varchar
  city varchar
  state_county varchar
  zip_post_code varchar
  country varchar
  Indexes {
    (id, org_name, type)
  }
}

Table case_worker {
  id integer [pk, increment]
  organisation foreign_key
  first_name varchar
  last_name varchar
  email varchar
  tel varchar(15)
}

Table wish_list {
  id integer [pk, increment]
  case_worker foreign_key
  wish_list_url varchar
}

Table wish_item {
  id integer [pk, increment]
  wish_list foreign_key
  status foreign_key
  product_name varchar
  image_link text
  needs tbc
  has tbc
  item_url text
  item_priority tbc
  created_at datetime
  updated_at datetime
}

Table item_status {
  id integer
  status varchar

  Indexes {
    (id, status) [unique]
  }
}

Ref organisation_address: organisation.address - organisation_address.(id, organisation, type)
Ref organisation: case_worker.organisation > organisation.id
Ref case_worker: wish_list.case_worker > case_worker.id
Ref wish_list: wish_item.wish_list > wish_list.id
Ref wish_item: wish_item.status - item_status.(id, status)
